stages:
  - test
  - build
  - deploy

test_rest-api:
  image: sdorra/oracle-java-8
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    when: on_failure
    paths:
      - '*/build/reports/*'

build_rest-api:
  image: sdorra/oracle-java-8
  stage: build
  script:
    - ./gradlew clean distZip
  artifacts:
    paths:
      - rest-api/build/distributions/*.zip

deploy_on_development:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth bot@nobt.io YP8y1NQCqdcbbgfdLw0b
    - cf target -o nobt.io -s development
  script:
    - cf push -n nobt-io-dev -p rest-api/build/distributions/*.zip
  except:
    - tags
  only:
    - master