image: registry.gitlab.com/nobt-io-public/api-build-image:2.1.0

stages:
  - build
  - deploy

build_rest-api:
  stage: build
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - ./gradlew clean
    - ./gradlew build
  artifacts:
    when: always
    paths:
      - 'rest-api/build/distributions/*.zip'
      - '*/build/reports/*'

deploy_on_development:
  stage: deploy
  script:
    - .aws/deploy api-prod
  only:
    - master