stages:
  - test
  - build
  - deploy

test_rest-api:
  image: sdorra/oracle-java-8
  stage: test
  script:
    - ./gradlew clean test
  artifacts:
    when: on_failure
    paths:
      - rest-api/build/reports/*

build_rest-api:
  image: sdorra/oracle-java-8
  stage: build
  script:
    - ./gradlew clean distZip
  artifacts:
    paths:
      - rest-api/build/distributions/*.zip

deploy_on_beta:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth c2895380@trbvn.com YP8y1NQCqdcbbgfdLw0b
    - cf target -o nobt.io -s beta
  script:
    - cf push -n nobt-io-beta -p rest-api/build/distributions/*.zip
  except:
    - tags
  only:
    - master

deploy_on_production:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth c2895380@trbvn.com YP8y1NQCqdcbbgfdLw0b
    - cf target -o nobt.io -s production
  script:
    - cf push -n nobt-io -p rest-api/build/distributions/*.zip
  only:
    - tags