image: registry.gitlab.com/nobt-io-public/api-build-image:1.0.3

stages:
  - build
  - deploy

build_rest-api:
  stage: build
  services:
    - postgres:9
  variables:
    DATABASE_CONNECTION_STRING: 'jdbc:postgresql://postgres:password@postgres:5432/postgres'
  script:
    - ./gradlew clean
    - ./gradlew test
    - ./gradlew integrationTest -Dorg.gradle.parallel=false # MUST NOT run integration tests in parallel
    - ./gradlew :rest-api:distZip
  artifacts:
    when: always
    paths:
      - 'rest-api/build/distributions/*.zip'
      - '*/build/reports/*'

deploy_on_development:
  stage: deploy
  before_script:
    - .bin/login.sh development
    - .bin/prepareEnv.sh
  script:
    - .bin/push.sh nobt-io-dev
  environment: development
  only:
    - master

deploy_on_beta:
  stage: deploy
  before_script:
    - .bin/login.sh beta
  script:
    - .bin/push.sh nobt-io-beta
  environment: beta
  when: manual

deploy_on_production:
  stage: deploy
  before_script:
    - .bin/login.sh production
  script:
    - .bin/push.sh nobt-io
  environment: production
  when: manual