stages:
  - build
  - deploy

build_rest-api:
  image: sdorra/oracle-java-8
  services:
    - docker:dind
  stage: build
  script:
    - ./gradlew clean build -Dorg.gradle.parallel=true
  artifacts:
    when: always
    paths:
      - 'rest-api/build/distributions/*.zip'
      - '*/build/reports/*'

deploy_on_development:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth bot@nobt.io YP8y1NQCqdcbbgfdLw0b
    - cf target -o nobt.io -s development
  script:
    - cf push -n nobt-io-dev -p rest-api/build/distributions/*.zip
  except:
    - tags
  only:
    - master