stages:
  - build
  - deploy

build_rest-api:
  image: openjdk:8
  stage: build
  services:
    - postgres:9
  variables:
    TEST_POSTGRES_HOST: 'postgres'
  before_script:
    - ./gradlew clean
  script:
    - ./gradlew integrationTest -Dorg.gradle.parallel=false # MUST NOT run integration tests in parallel
    - ./gradlew test -x integrationTest -Dorg.gradle.parallel=true # unit tests are fine to be run in parallel
    - ./gradlew :rest-api:distZip
  artifacts:
    when: always
    paths:
      - 'rest-api/build/distributions/*.zip'
      - '*/build/reports/*'

deploy_on_development:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth bot@nobt.io YP8y1NQCqdcbbgfdLw0b
    - cf target -o nobt.io -s development
  script:
    - cf push -n nobt-io-dev -p rest-api/build/distributions/*.zip
  only:
    - master