stages:
  - build
  - deploy

build_rest-api:
  image: openjdk:8 # TODO we should use a slimmer image here, only need java and bash
  stage: build
  services:
    - postgres:9
  variables:
    DATABASE_CONNECTION_STRING: 'jdbc:postgresql://postgres:password@postgres:5432/postgres'
  script:
    - ./gradlew test -x integrationTest -Dorg.gradle.parallel=true # unit tests are fine to be run in parallel
    - ./gradlew integrationTest -Dorg.gradle.parallel=false # MUST NOT run integration tests in parallel
    - ./gradlew :rest-api:distZip
  artifacts:
    when: always
    paths:
      - 'rest-api/build/distributions/*.zip'
      - '*/build/reports/*'

deploy_on_development:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
    - cf api https://api.run.pivotal.io
    - cf auth $CF_BUILD_USER $CF_BUILD_USER_PASSWORD
    - cf target -o nobt.io -s development
  script:
    - cf push -n nobt-io-dev -p rest-api/build/distributions/*.zip
  environment: development
  only:
    - master

deploy_on_beta:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
      - cf api https://api.run.pivotal.io
      - cf auth $CF_BUILD_USER $CF_BUILD_USER_PASSWORD
      - cf target -o nobt.io -s beta
  script:
      - cf push -n nobt-io-beta -p rest-api/build/distributions/*.zip
  environment: beta
  when: manual

deploy_on_production:
  image: governmentpaas/cf-cli
  stage: deploy
  before_script:
      - cf api https://api.run.pivotal.io
      - cf auth $CF_BUILD_USER $CF_BUILD_USER_PASSWORD
      - cf target -o nobt.io -s production
  script:
      - cf push -n nobt-io -p rest-api/build/distributions/*.zip
  environment: production
  when: manual